version: "3.9"
services:
  customer-service:
    build: .
    ports:
      - "8088:8088"
    environment:
      - MYSQL_HOST=mysql-customer
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=db_customer

  item-service:
    image: ghcr.io/umm-a/item-service
    ports:
      - "8083:8083"
    environment:
      - MYSQL_HOST=mysql-item
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=db_item

  mysql-customer:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=db_customer

  mysql-item:
    image: mysql:latest
    ports:
      - "3306:3306" # ÄNDRA FÖRSTA SIFFRAN OM MARIA ÄNDRAR I SIN APPLICATION:PROPERTIES
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=db_item
